# Generated by Django 4.1 on 2022-08-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
